image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Fly CLI & Dependencies
    init: |
      curl -L https://fly.io/install.sh | sh
      export FLYCTL_INSTALL="/home/gitpod/.fly"
      export PATH="$FLYCTL_INSTALL/bin:$PATH"
      echo 'export PATH="$FLYCTL_INSTALL/bin:$PATH"' >> ~/.bashrc
    command: |
      export FLYCTL_INSTALL="/home/gitpod/.fly"
      export PATH="$FLYCTL_INSTALL/bin:$PATH"
      fly version

  - name: Setup Python Environment
    init: pip install -r requirements.txt

ports:
  - port: 8080
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
