services:
  - type: web
    name: stellar-bot
    env: docker  # ← ЭТО КЛЮЧ! Не "python", а "docker"
    plan: free
    region: oregon
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
