services:
  - type: web
    name: stellar-bot
    env: python
    plan: free
    runtime: python-3.11  # ← ЯВНО указываем версию 3.11!
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
